# Generated by nixos-generate-config — replace this entire file with YOUR
# /etc/nixos/hardware-configuration.nix after running:
#   nixos-generate-config --root /mnt   (during install)
# or:
#   nixos-generate-config --show-hardware-config > hardware-configuration.nix

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # ── Boot kernel modules ───────────────────────────────────────────────────
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules          = [];
  boot.kernelModules                 = [ "kvm-amd" ]; # or kvm-intel
  boot.extraModulePackages           = [];

  # ── Filesystems ───────────────────────────────────────────────────────────
  # Replace UUIDs with output from: lsblk -f
  fileSystems."/" = {
    device  = "/dev/disk/by-uuid/<CHANGE_ME>";
    fsType  = "ext4";
  };

  fileSystems."/boot" = {
    device  = "/dev/disk/by-uuid/<CHANGE_ME>";
    fsType  = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [];

  # ── CPU ───────────────────────────────────────────────────────────────────
  hardware.cpu.amd.updateMicrocode   = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
